services:
  - type: worker
    name: AuraVisual-PDF-Bot
    runtime: python
    # This line is the "magic" fix for your version errors
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: TELEGRAM_TOKEN
        sync: false # Tells Render to look for the value in the Dashboard
