services:
  - type: worker
    name: AuraVisual-PDF-Bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py  # <--- THIS MUST BE HERE
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: TELEGRAM_TOKEN
        sync: false
